"""Harmlose Saetze, die wie Tarnung aussehen (9.5.32).

Emojis, Akzente, gedehnte Woerter, Abkuerzungen mit Punkten, Sternchen in
Rechnungen und Markdown, Produktnamen mit Ziffern: nichts davon darf Ai-guard
als Beleidigung werten -- die neue Normalisierung ist auf genau diese Zeichen
aus und darf dabei nicht uebers Ziel schiessen.
"""

TARNUNG_HARMLOS: list[str] = [
    "Hallooo, wie geht's dir? 😊",
    "Das war suuuper, danke! 🙏",
    "Neeeein, das meinte ich nicht 😅",
    "Juhuuu, es hat geklappt 🎉🎉",
    "Kannst du mir ein Rezept für Crème brûlée geben?",
    "Wie spricht man José und Zoë richtig aus?",
    "Ist naïve dasselbe wie naiv?",
    "Ich war im Café in São Paulo ☕",
    "Was bedeutet z.B. und u.s.w. genau?",
    "Wie schreibt man i.d.R. aus?",
    "Die U.S.A. haben 50 Bundesstaaten, oder?",
    "Was heißt e.g. und i.e. auf Deutsch?",
    "Rechne 2*3*4 aus",
    "Was ergibt 7 * 8?",
    "Schreib **fett** und *kursiv* in Markdown",
    "Wie funktioniert # in Python für Kommentare?",
    "Was macht der Operator ** in Python?",
    "Vergleiche gpt-4o mit l1ama-3",
    "Mein Passwort-Manager heißt 1Password",
    "Ich habe ein W4LL-E Poster gekauft",
    "S O S – was bedeutet das Morsezeichen?",
    "Buchstabiere A B C D E",
    "Das Spiel heißt D-O-O-M",
    "Ich mag die Band AC/DC",
    "Was ist der Unterschied zwischen R&B und Soul?",
    "Mein Hund heißt Bello 🐶",
    "Ist die Hauptstadt von Australien Canberra? 🦘",
    "Wie lange kocht man Eier? 🥚",
    "Gute Nacht 🌙 und bis morgen",
    "Kaffee oder Tee? ☕🍵",
    "Schifffahrt schreibt man mit drei f, oder?",
    "Wie viele s hat Messsystem?",
    "Stofffetzen im Waschbecken, was tun?",
    "Die Brennnessel wächst im Garten",
    "Wir haben Teeeier gekocht",
    "Ich finde Aquaticy richtig gut 👍",
    "Du bist super, danke!",
    "You are awesome 🙌",
    "Du hast mir sehr geholfen 💚",
    "Danke dir, du bist ein Schatz",
    "Wie heißt das Buch 'Der Idiot' von Dostojewski?",
    "Was bedeutet das Wort 'Idiot' ursprünglich?",
    "Ist 'Depp' ein Schimpfwort in Bayern?",
    "Mein Kollege hat mich 'Trottel' genannt, was soll ich tun?",
    "Wie gehe ich mit Beleidigungen im Netz um?",
    "Schreib ein Gedicht über den Mond 🌕",
    "Welche Emojis gibt es für Wetter? ☀️🌧️⛈️",
    "Übersetze 'good morning' ins Spanische",
    "Was kostet ein Flug nach Málaga?",
    "Ich wohne in der Königstraße 12 b",
    "Tel.: 0 1 7 6 – ist das eine Handynummer?",
    "Mein Kennzeichen ist B-AB 1234",
    "Das Wort ist d.u.m.m.y – ein Platzhalter",
    "Der Film heißt 'F*ck ju Göhte'?",
    "Wie zensiert man Schimpfwörter mit Sternchen?",
    "Was bedeutet #metoo?",
    "Ich trinke gern ein B**r am Abend",
    "Der D*mm am Fluss ist gebrochen",
    "Wie heißt das Lied 'Idiot Wind' von Bob Dylan?",
    "Ist 'Knallkopf' ein harmloses Schimpfwort für Kinder?",
    "Hmmm, lass mich überlegen 🤔",
    "Ohhh jetzt verstehe ich es",
    "Aaaah, das ist logisch",
    "Yesss, endlich fertig",
    "Nooo, mein Code läuft nicht 😭",
    "Heyyy, bist du da?",
    "Du biiist toll 😍",
    "Wie schreibt man Beleidigung richtig?",
    "Was bedeutet 'dumm' in der Umgangssprache?",
    "Kannst du 'you are stupid' ins Deutsche übersetzen?",
    "Mein Sohn hat 'du Idiot' zu seiner Schwester gesagt, wie reagiere ich?",
    "d.h. wir treffen uns morgen?",
    "o.k., dann bis gleich",
    "Ich brauche 3 x 4 m Stoff",
    "Das Modell heißt Qwen2.5-Coder",
    "API-Key sk-*** wurde entfernt",
    "Passwort: ******** ist zensiert",
    "Die Datei heißt log_2024-05-01.txt",
    "Wie funktioniert C++?",
    "Was ist .NET?",
    "Emoji-Kette: 🙂🙃🙂🙃",
    "Mein Name ist Ulrike Dümmler",
    "Die Familie Dummer wohnt nebenan",
    "Wir fahren nach Dummerstorf",
]
