"""Begruessungen und Vorschlaege auf der leeren Startseite (seit 9.6.0).

Jeder neue Chat zieht zufaellig einen Satz und drei Vorschlaege -- je Modus
eigene, mindestens 50 von jedem. In einem Satz steht ``{gruss}`` fuer die
Tageszeit ("Guten Morgen", kennt nur das Geraet des Nutzers) und ``{name}``
fuer den Nutzernamen; ohne Namen faellt ", {name}" samt Komma weg.
"""

from __future__ import annotations

GREETINGS: dict[str, tuple[str, ...]] = {
    "normal": (
        "{gruss}, {name}. Wobei kann ich dir helfen?",
        "{gruss}, {name}. Was möchtest du heute herausfinden?",
        "{gruss}, {name}. Was schauen wir uns an?",
        "{gruss}, {name}. Worüber willst du mehr wissen?",
        "{gruss}, {name}. Was liegt heute an?",
        "Schön, dass du da bist, {name}. Was suchen wir?",
        "Hallo {name}, was darf ich für dich nachschlagen?",
        "Na, {name}, was geht dir gerade durch den Kopf?",
        "Was möchtest du wissen, {name}?",
        "Frag mich einfach, {name}.",
        "Womit fangen wir an, {name}?",
        "Ich bin bereit, {name}. Was steht an?",
        "Was darf es heute sein, {name}?",
        "Eine Frage, ein Plan, eine Idee? Ich höre zu, {name}.",
        "Was soll ich für dich im Web finden, {name}?",
        "Lass uns etwas herausfinden, {name}.",
        "Erzähl, {name}: Was interessiert dich gerade?",
        "Neugierig auf etwas, {name}?",
        "Ich suche, lese und fasse zusammen. Was brauchst du, {name}?",
        "Wo drückt der Schuh, {name}?",
        "Bereit für eine neue Frage, {name}?",
        "Was willst du heute klären, {name}?",
        "Gib mir ein Thema, {name}, ich kümmere mich um den Rest.",
        "Wie kann ich dir den Tag leichter machen, {name}?",
        "Was recherchieren wir heute, {name}?",
        "Ich habe Zeit, {name}. Was liegt dir auf dem Herzen?",
        "Ein frischer Chat, {name}. Was soll rein?",
        "Was wolltest du schon immer mal wissen, {name}?",
        "Suchst du etwas Bestimmtes, {name}?",
        "Was planen wir, {name}?",
        "Sag mir, was du brauchst, {name}.",
        "Heute schon etwas Neues gelernt, {name}? Ich helfe gern.",
        "Womit kann ich dich überraschen, {name}?",
        "Ich bin ganz Ohr, {name}.",
        "Auf geht's, {name}. Was ist deine Frage?",
        "Was soll ich für dich vergleichen, prüfen oder erklären, {name}?",
        "Lust auf eine kleine Recherche, {name}?",
        "{gruss}! Was darf ich herausfinden, {name}?",
        "{gruss}, {name}. Wie kann ich helfen?",
        "{gruss}, {name}. Was gibt's Neues?",
        "Was beschäftigt dich, {name}?",
        "Ein neues Thema, {name}? Leg los.",
        "Ich finde es für dich heraus, {name}. Was ist es?",
        "Was willst du verstehen, {name}?",
        "Wohin soll die Reise heute gehen, {name}?",
        "Gute Frage parat, {name}?",
        "Lass mich dir etwas Arbeit abnehmen, {name}.",
        "Was steht heute auf deiner Liste, {name}?",
        "Was darf ich für dich klären, {name}?",
        "Nur zu, {name}, frag mich alles.",
        "Ein neuer Anfang, {name}. Worum geht's?",
        "Lass hören, {name}: Was suchen wir heute?",
    ),
    "pro": (
        "{gruss}, {name}. Welche große Frage nehmen wir uns vor?",
        "{gruss}, {name}. Was soll ich gründlich recherchieren?",
        "{gruss}, {name}. Woran arbeiten wir heute in Ruhe?",
        "Zeit für etwas Größeres, {name}?",
        "Was soll ich bis ins Detail prüfen, {name}?",
        "Gib mir ein schweres Thema, {name}.",
        "Wir können tief graben, {name}. Womit fangen wir an?",
        "Was braucht heute mehr als eine schnelle Antwort, {name}?",
        "Bereit für eine richtige Recherche, {name}?",
        "Welches Projekt bringen wir voran, {name}?",
        "Ich nehme mir Zeit, {name}. Worum geht es?",
        "Lass uns etwas gründlich durchdenken, {name}.",
        "Welche Entscheidung soll ich dir vorbereiten, {name}?",
        "Was soll ich aus mehreren Quellen zusammentragen, {name}?",
        "Ein großes Thema, {name}? Her damit.",
        "Was willst du wirklich verstehen, {name}?",
        "Ich schicke gern mehrere Agenten los, {name}. Wofür?",
        "Was soll ich vergleichen, bewerten und belegen, {name}?",
        "Komplexe Frage, {name}? Genau dafür bin ich hier.",
        "Wo brauchst du einen gründlichen Überblick, {name}?",
        "Lass uns heute in die Tiefe gehen, {name}.",
        "Welche Analyse darf es sein, {name}?",
        "Womit soll ich mich ausführlich beschäftigen, {name}?",
        "Was ist dein Vorhaben, {name}?",
        "Was soll am Ende auf dem Tisch liegen, {name}?",
        "Ein Bericht, ein Vergleich, ein Plan? Sag es mir, {name}.",
        "Heute nehmen wir uns Zeit, {name}. Was steht an?",
        "Welche Frage verdient eine ausführliche Antwort, {name}?",
        "{gruss}! Was soll ich für dich ausarbeiten, {name}?",
        "{gruss}, {name}. Bereit für die gründliche Variante?",
        "Was willst du mit Belegen wissen, {name}?",
        "Ich prüfe gern doppelt, {name}. Worum geht's?",
        "Welche Marktübersicht brauchst du, {name}?",
        "Lass uns ein schwieriges Problem zerlegen, {name}.",
        "Was soll ich Schritt für Schritt untersuchen, {name}?",
        "Ein großer Auftrag, {name}? Ich bin bereit.",
        "Was soll ich heute für dich durchleuchten, {name}?",
        "Welche Fakten soll ich sauber zusammentragen, {name}?",
        "Gründlich statt schnell, {name}. Was ist das Thema?",
        "Was willst du heute endlich wissen, {name}?",
        "Wir haben Zeit für Details, {name}. Leg los.",
        "Welche Strategie arbeiten wir aus, {name}?",
        "Wie tief sollen wir graben, {name}?",
        "Gib mir eine harte Nuss, {name}.",
        "Was soll ich für dich bewerten, {name}?",
        "Wofür brauchst du heute eine fundierte Antwort, {name}?",
        "Lass uns etwas Ordentliches bauen, {name}: Recherche, Plan, Ergebnis.",
        "Welches Thema soll ich von allen Seiten beleuchten, {name}?",
        "Ein neuer Chat für ein großes Thema, {name}?",
        "Was planen wir langfristig, {name}?",
        "Was soll ich dir heute gründlich erklären, {name}?",
        "Bereit, {name}. Welche Frage hat Gewicht?",
    ),
    "code": (
        "{gruss}, {name}. Was wollen wir bauen?",
        "{gruss}, {name}. Welches Problem lösen wir?",
        "{gruss}, {name}. Woran programmieren wir heute?",
        "Welcher Bug nervt dich heute, {name}?",
        "Was soll ich für dich coden, {name}?",
        "Editor offen, {name}. Was steht an?",
        "Bereit zum Bauen, {name}?",
        "Welches Skript brauchst du, {name}?",
        "Zeig mir den Code, {name}.",
        "Was soll laufen, das gerade nicht läuft, {name}?",
        "Ein neues Projekt, {name}? Erzähl.",
        "Was refaktorieren wir heute, {name}?",
        "Welche Tests fehlen noch, {name}?",
        "Stacktrace dabei, {name}? Her damit.",
        "Was automatisieren wir heute, {name}?",
        "Lass uns etwas Sauberes bauen, {name}.",
        "Welche Funktion soll ich schreiben, {name}?",
        "Woran hängt es gerade, {name}?",
        "Was darf ich debuggen, {name}?",
        "Welche Sprache sprechen wir heute, {name}: Python, JavaScript, Go?",
        "Kaffee ist bereit, {name}. Der Code auch?",
        "Was soll ich erklären, {name}: Code, Fehler oder Idee?",
        "Ein kleines Tool gefällig, {name}?",
        "Was soll ich prüfen, {name}?",
        "Welche API bauen wir, {name}?",
        "Was willst du heute ausliefern, {name}?",
        "Commit-bereit, {name}? Dann los.",
        "Gib mir eine Aufgabe, {name}, ich schreibe den Code.",
        "Welche Datenbank-Abfrage machen wir schneller, {name}?",
        "Welcher Fehler raubt dir den Schlaf, {name}?",
        "Was soll in die virtual machine, {name}?",
        "Lass uns ein Problem in kleine Schritte zerlegen, {name}.",
        "Was baust du gerade, {name}?",
        "Ein Prototyp, {name}? Ich bin dabei.",
        "Was soll ich für dich umschreiben, {name}?",
        "Welche Datei schauen wir uns an, {name}?",
        "{gruss}! Was coden wir, {name}?",
        "{gruss}, {name}. Bereit für ein paar Zeilen Code?",
        "Welche Idee machen wir lauffähig, {name}?",
        "Was soll schneller, schöner oder sicherer werden, {name}?",
        "Welche Bibliothek soll ich dir erklären, {name}?",
        "Ein Regex-Problem, {name}? Ich mag die.",
        "Welches Shell-Skript brauchst du, {name}?",
        "Was willst du heute verstehen, {name}: einen Algorithmus vielleicht?",
        "Was testen wir zuerst, {name}?",
        "Lass uns den Code aufräumen, {name}.",
        "Was soll ich dokumentieren, {name}?",
        "Welche Fehlermeldung soll ich übersetzen, {name}?",
        "Was bauen wir als Nächstes, {name}?",
        "Ein frischer Branch, {name}. Was kommt rein?",
        "Gib mir den Fehler, {name}, ich finde die Ursache.",
        "Bereit, {name}. Welches Programm schreiben wir?",
    ),
}

SUGGESTIONS: dict[str, tuple[str, ...]] = {
    "normal": (
        "Was ist heute in meiner Stadt los?",
        "Finde ein gutes Café mit WLAN in meiner Nähe",
        "Vergleiche drei Laptops für Bildbearbeitung",
        "Erkläre mir, wie eine Wärmepumpe funktioniert",
        "Welche Geräte hängen in meinem Netz?",
        "Plane einen entspannten Tagesausflug",
        "Fasse die wichtigsten Nachrichten zusammen",
        "Hilf mir bei einer Kaufentscheidung",
        "Prüfe diese Behauptung mit mehreren Quellen",
        "Wie wird das Wetter am Wochenende?",
        "Günstige Flüge nach Lissabon im Mai",
        "Ein schnelles Rezept mit Nudeln und Spinat",
        "Welche Serien lohnen sich gerade?",
        "Erkläre mir den Unterschied zwischen ETF und Fonds",
        "Tipps für besseren Schlaf",
        "Was kann ich heute Abend kochen?",
        "Welche Pflanzen vertragen wenig Licht?",
        "Wie spare ich Strom im Haushalt?",
        "Ideen für ein Geburtstagsgeschenk unter 30 €",
        "Was bedeutet Inflation einfach erklärt?",
        "Die besten Wanderwege in meiner Nähe",
        "Wie funktioniert eigentlich KI?",
        "Welche Museen haben am Sonntag offen?",
        "Hilf mir, eine Bewerbung zu formulieren",
        "Was muss ich beim Gebrauchtwagenkauf beachten?",
        "Erkläre mir die Mondphasen",
        "Welche E-Bikes sind gerade empfehlenswert?",
        "Fasse mir dieses PDF zusammen",
        "Wie wird man Mitglied in einem Sportverein?",
        "Plane mir eine Woche gesunde Ernährung",
        "Welche Konzerte gibt es diesen Monat?",
        "Wie entferne ich Kalk aus dem Wasserkocher?",
        "Was ist der Unterschied zwischen Wetter und Klima?",
        "Ideen für einen Regentag mit Kindern",
        "Wie funktioniert die Mülltrennung richtig?",
        "Welche Bücher passen zu meinem Geschmack?",
        "Erkläre mir, wie Zinsen berechnet werden",
        "Wo kann ich am Wochenende frühstücken?",
        "Was sind die neuesten Nachrichten?",
        "Wie lerne ich am schnellsten eine neue Sprache?",
        "Vergleiche Handytarife unter 15 €",
        "Welche Feiertage kommen als Nächstes?",
        "Wie pflege ich meine Laufschuhe?",
        "Erkläre mir ein Thema wie für Fünfjährige",
        "Was kostet ein Wochenende in Amsterdam?",
        "Welche Kopfhörer mit Geräuschunterdrückung?",
        "Was hilft gegen Erkältung?",
        "Wie schreibe ich eine höfliche Beschwerde?",
        "Plane eine Radtour mit Einkehr",
        "Wie funktioniert ein Sparplan?",
        "Welche Brettspiele sind gut für zwei?",
        "Was sind gute Übungen für den Rücken?",
        "Wie viel Trinkgeld gibt man in den USA?",
        "Fasse diese Webseite für mich zusammen",
    ),
    "pro": (
        "Erstelle einen Marktüberblick über Wärmepumpen mit Preisen",
        "Vergleiche fünf Elektroautos nach Reichweite und Kosten",
        "Recherchiere die Vor- und Nachteile von Balkonkraftwerken",
        "Arbeite einen Umzugsplan mit Fristen und Checkliste aus",
        "Prüfe diese Studie: Wie belastbar sind die Ergebnisse?",
        "Erstelle einen Reiseplan für zwei Wochen Japan",
        "Vergleiche Krankenkassen nach Zusatzleistungen",
        "Fasse den aktuellen Stand der Forschung zu Schlaf zusammen",
        "Plane ein Budget für meinen ersten eigenen Haushalt",
        "Wie entwickelt sich der Wohnungsmarkt in meiner Stadt?",
        "Vergleiche Girokonten ohne Kontoführungsgebühr",
        "Erstelle eine Entscheidungshilfe: Mieten oder kaufen?",
        "Recherchiere Fördermittel für eine energetische Sanierung",
        "Analysiere die Argumente für und gegen ein Tempolimit",
        "Stelle einen Trainingsplan für einen Halbmarathon zusammen",
        "Vergleiche Cloud-Speicher nach Datenschutz und Preis",
        "Erkläre mir die Geschichte der Europäischen Union ausführlich",
        "Erstelle einen Businessplan-Entwurf für ein kleines Café",
        "Welche Laptops eignen sich für Videoschnitt? Mit Begründung",
        "Recherchiere die besten Wege, Englisch beruflich zu verbessern",
        "Vergleiche Photovoltaik-Angebote: worauf muss ich achten?",
        "Fasse die wichtigsten Nachrichten der Woche mit Quellen zusammen",
        "Erstelle einen Lernplan für die Mathe-Prüfung",
        "Untersuche, welche Smartphones am längsten Updates bekommen",
        "Plane eine Hochzeit mit 60 Gästen: Kosten und Zeitplan",
        "Vergleiche Streamingdienste nach Angebot und Preis",
        "Recherchiere die Fakten zu einer viralen Behauptung",
        "Erstelle eine Übersicht über Altersvorsorge-Möglichkeiten",
        "Analysiere die Vor- und Nachteile von Homeoffice",
        "Vergleiche E-Bikes bis 3000 € mit Testberichten",
        "Erarbeite eine Strategie, um 20 % Stromkosten zu sparen",
        "Recherchiere seriöse Online-Kurse für Datenanalyse",
        "Erstelle einen Vergleich der Bahn- und Flugreise nach Rom",
        "Fasse ein Fachthema auf drei Seiten verständlich zusammen",
        "Untersuche die Klimabilanz verschiedener Ernährungsweisen",
        "Plane eine Gartenumgestaltung mit Pflanzliste",
        "Vergleiche Versicherungen für Fahrräder",
        "Recherchiere, wie man eine Firma in Deutschland gründet",
        "Erstelle eine Pro-und-Contra-Liste für einen Jobwechsel",
        "Analysiere die Entwicklung der Strompreise der letzten Jahre",
        "Vergleiche Saugroboter nach Leistung und Lautstärke",
        "Erstelle einen Wochenplan für Familie und Beruf",
        "Recherchiere die besten Reiseziele für den Herbst",
        "Untersuche, welche Kamera sich für Einsteiger lohnt",
        "Fasse die Rechtslage zu einem Mietproblem verständlich zusammen",
        "Plane eine Renovierung mit Kostenschätzung",
        "Vergleiche Sprachlern-Apps nach Methode und Preis",
        "Erstelle eine Präsentationsgliederung zu meinem Thema",
        "Recherchiere Studien zur Wirkung von Intervallfasten",
        "Vergleiche Mobilfunknetze in meiner Region",
        "Analysiere einen Text auf Argumente und Schwächen",
        "Erstelle einen Überblick über die besten Spartipps im Alltag",
        "Recherchiere Ausbildungsberufe mit guter Zukunft",
    ),
    "code": (
        "Schreib ein Python-Skript, das Ordner nach Datum sortiert",
        "Warum wirft dieser Code einen IndexError?",
        "Baue eine kleine REST-API mit FastAPI",
        "Verbessere die Fehlermeldungen in diesem Programm",
        "Schreib Tests für diese Funktion",
        "Vereinfache diesen Code, ohne sein Verhalten zu ändern",
        "Finde den Fehler in diesem Stacktrace",
        "Entwirf eine kleine Kommandozeilen-App",
        "Optimiere diese Datenbankabfrage",
        "Schreib ein Bash-Skript für tägliche Backups",
        "Erkläre mir async und await in Python",
        "Baue eine To-do-App mit HTML und JavaScript",
        "Wandle diese CSV-Datei in JSON um",
        "Schreib einen regulären Ausdruck für E-Mail-Adressen",
        "Erkläre mir Git-Branches mit Beispielen",
        "Baue einen Web-Scraper, der robots.txt achtet",
        "Mach aus dieser Funktion eine Klasse",
        "Schreib ein Dockerfile für meine Python-App",
        "Wie funktioniert Rekursion? Mit Beispiel",
        "Schreib eine SQL-Abfrage für die Top-10-Kunden",
        "Erstelle ein Diagramm aus diesen Daten mit matplotlib",
        "Prüfe meinen Code auf Sicherheitslücken",
        "Baue einen Discord-Bot-Grundgerüst",
        "Schreib Typ-Hinweise für dieses Modul",
        "Erkläre den Unterschied zwischen Liste und Tupel",
        "Baue einen Passwort-Generator",
        "Schreib ein Skript, das doppelte Dateien findet",
        "Mach diesen Code schneller",
        "Erstelle eine einfache Login-Seite mit Flask",
        "Erkläre mir Big-O an einem Beispiel",
        "Schreib einen Unit-Test mit pytest",
        "Baue eine kleine Wetter-App mit einer freien API",
        "Konvertiere dieses Skript nach TypeScript",
        "Schreib eine GitHub-Actions-Pipeline für Tests",
        "Finde das Speicherleck in diesem Code",
        "Baue einen Taschenrechner für die Kommandozeile",
        "Erkläre mir Dekoratoren in Python",
        "Schreib ein Skript, das Bilder verkleinert",
        "Lies eine Excel-Datei mit pandas aus",
        "Baue eine einfache Warteschlange mit Threads",
        "Erkläre mir, was ein Closure ist",
        "Schreib eine Funktion, die Primzahlen findet",
        "Formatiere diesen JSON-Code sauber",
        "Baue ein Spiel: Schere, Stein, Papier",
        "Wie strukturiere ich ein größeres Python-Projekt?",
        "Schreib ein Logging-Setup für meine App",
        "Erkläre mir HTTP-Statuscodes",
        "Baue einen Countdown-Timer in JavaScript",
        "Schreib eine Funktion zum Validieren von IBANs",
        "Räume diese Abhängigkeiten auf",
        "Erkläre mir diesen Code Zeile für Zeile",
        "Schreib ein Makefile für mein Projekt",
        "Baue eine Markdown-zu-HTML-Umwandlung",
    ),
}
